image: "node:18-slim"

stages:
  - build
  - publish

build:node-build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    when: always
    paths:
      - build
    expire_in: 24h

publish:docker:
  stage: publish
  image: "docker:20.10"
  needs:
    - "build:node-build"
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:$CI_COMMIT_REF_SLUG
    IMAGE_LATEST: ${CI_REGISTRY_IMAGE}:latest
  services:
    - name: docker:20.10-dind
      alias: docker
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - if [[ "$CI_COMMIT_REF_SLUG" == "main" ]]; then
      docker build -f docker/Dockerfile --cache-from ${IMAGE_LATEST} -t ${IMAGE_TAG} -t ${IMAGE_LATEST} .;
      docker push ${IMAGE_TAG};
      docker push ${IMAGE_LATEST};
      else
      docker build -f docker/Dockerfile --cache-from ${IMAGE_TAG} -t ${IMAGE_TAG} .;
      docker push ${IMAGE_TAG};
      fi
