extends:
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
rules:
  alpha-value-notation: number
  at-rule-no-unknown: null
  color-function-notation: legacy
  declaration-colon-newline-after: null
  font-family-no-missing-generic-family-keyword:
    - true
    - ignoreFontFamilies: ["Font Awesome 5 Free"]
  no-descending-specificity: null
  no-invalid-position-at-import-rule: null
  scss/no-global-function-names: null
  selector-class-pattern:
    - ^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$
    - message: Expected class selector to be kebab-case or BEM
  value-list-comma-newline-after: null
